### PR TITLE
Update autoexec.ash

### PR DESCRIPTION
**Pull request by waynosilverbullet**

### CODE REVIEW

**Comment by waynosilverbullet** [comment]
One frame every 5mins with wifi reboot

**Comment by KonradIT** [comment]
@waynosilverbullet you cannot push to hacks that are not yours

**Comment by waynosilverbullet** [comment]
Hi

I have no idea what that means, sorry.
Wayne de Lange

**Comment by KonradIT** [comment]
@waynosilverbullet check your email inbox

**Pull request closed without merging**
