### PR TITLE
Update autoexec.ash

### PR DESCRIPTION
**Pull request by AcidONE**

### CODE REVIEW

**Comment by KonradIT** [comment]
Please pull to your custom autoexec hack

**Comment by AcidONE** [comment]
pls create this for me and i try:

sleep 3
t app appmode photo
sleep 4
t app button shutter PR
sleep 6
t app appmode video
sleep 3
t app button shutter PR
sleep 45
t app button shutter PR
sleep 6
t app appmode photo
sleep 4
t app button shutter PR
sleep 6
t app appmode video
sleep 3
t app button shutter PR
sleep 45
t app button shutter PR
d:\autoexec.ash
REBOOT yes

Il giorno 27/giu/2014, alle ore 17:00, Konrad Iturbe notifications@github.com ha scritto:

**Comment by AcidONE** [comment]
hi, works perfectly … thanks
Now you can match to my autoexec fisheye removal?

t ia2 -fisheye 1 65536 65536 65536 65536 100
t ia2 -warp 0
sleep 3 
t app appmode photo 
sleep 4 
t app button shutter PR 
sleep 6 
t app appmode video 
sleep 3 
t app button shutter PR 
sleep 45 
t app button shutter PR 
sleep 6 
t app appmode photo 
sleep 4 
t app button shutter PR 
sleep 6 
t app appmode video 
sleep 3 
t app button shutter PR 
sleep 45 
t app button shutter PR 
d:\autoexec.ash 
REBOOT yes

so many thanks
masismo

Il giorno 27/giu/2014, alle ore 17:00, Konrad Iturbe notifications@github.com ha scritto:

**Comment by KonradIT** [comment]
Closed #10

**Comment by KonradIT** [comment]
@AcidONE added fisheye removal code.

**Comment by AcidONE** [comment]
but it is all on one line ... it works the same?

Il giorno 30/giu/2014, alle ore 21:27, Konrad Iturbe notifications@github.com ha scritto:

**Comment by KonradIT** [comment]
@AcidONE yes

**Comment by AcidONE** [comment]
don’t works…1 string!!
pls correct this
thx

Il giorno 30/giu/2014, alle ore 21:49, Konrad Iturbe notifications@github.com ha scritto:

**Comment by AcidONE** [comment]
Hello, the auto exec fisheye removal don’t work to 2.7k 17:9 24 M and 2.7k 25 M, why??
can you correct this bug??
thx

Il giorno 30/giu/2014, alle ore 21:49, Konrad Iturbe notifications@github.com ha scritto:

**Comment by KonradIT** [comment]
@acidone i dont have a plus black, I suppose you have it because medium and narrow in 2.7k.
Could you send me a video shot in 2.7k M pointing to the floor 5m away, the same with narrow

**Comment by AcidONE** [comment]
pls very important for me…create this autoexec.
thx

t ia2 -fisheye 1 65536 65536 65536 65536 100
t ia2 -warp 0
sleep 3 
t app appmode photo 
sleep 4 
t app button shutter PR 
sleep 6 
t app appmode video 
sleep 3 
t app button shutter PR 
sleep 45 
t app button shutter PR 
sleep 6 
t app appmode photo 
sleep 4 
t app button shutter PR 
sleep 6 
t app appmode video 
sleep 3 
t app button shutter PR 
sleep 45 
t app button shutter PR 
d:\autoexec.ash 
REBOOT yes

Il giorno 01/lug/2014, alle ore 14:26, Konrad Iturbe notifications@github.com ha scritto:

**Comment by AcidONE** [comment]
now the auto exec works correctly but fishyeremoval to 2.7k or wide or medium don’t start. you have any idea?

Il giorno 01/lug/2014, alle ore 14:26, Konrad Iturbe notifications@github.com ha scritto:

**Comment by KonradIT** [comment]
@AcidONE dont know, tested on my black and it works.

**Pull request closed without merging**
